Repository j1y0ungyoon/gym-tivation, pull requests merged in 2023-03, with the labels that each got.

#68 Feat : apply main slider
  package.json
  pages/index.tsx
  styles/theme.ts
  yarn.lock
Labels: enhancement

#76 Refactor : ui
  components/DmChat.tsx
  components/SideNav.tsx
  pages/chat/index.tsx
  styles/theme.ts
Labels: refactor

#82 Feat : apply dmButton
  components/DmButton.tsx
  components/DmChat.tsx
  components/ProfileEdit.tsx
  package.json
  pages/_app.tsx
  pages/chat/index.tsx
  recoil/dmData.ts
  yarn.lock
Labels: enhancement

#83 Feat: apply global modal
  .env
  components/Comment.tsx
  components/SearchMyGym.tsx
  components/common/globalModal/AlertModal.tsx
  components/common/globalModal/ConfirmModal.tsx
  components/common/globalModal/GlobalModal.tsx
  hooks/useModal.ts
  pages/_app.tsx
  pages/mapBoard/WritingRecruitment.tsx
  pages/mapBoard/index.tsx
  pages/recruitDetail/[...params].tsx
  recoil/modalState.ts
Labels: enhancement

#84 Refactor : refactor main slide, ui
  components/SideNav.tsx
  pages/index.tsx
  public/assets/icons/nav/nav_board.svg
  public/assets/icons/nav/nav_board_active.svg
  public/assets/icons/nav/nav_chat.svg
  public/assets/icons/nav/nav_chat_active.svg
  public/assets/icons/nav/nav_gallery.svg
  public/assets/icons/nav/nav_gallery_active.svg
  public/assets/icons/nav/nav_home.svg
  public/assets/icons/nav/nav_home_active.svg
  public/assets/icons/nav/nav_my.svg
  public/assets/icons/nav/nav_my_active.svg
  public/assets/icons/nav/nav_recruit.svg
  public/assets/icons/nav/nav_recruit_active.svg
  public/assets/icons/next.svg
  public/assets/icons/prev.svg
  public/assets/icons/title.svg
Labels: refactor

#85 Feat : apply chat user search
  pages/chat/index.tsx
  pages/signIn/index.tsx
  pages/signUp/index.tsx
  public/assets/icons/closeBtn.svg
Labels: enhancement, refactor

#98 Fix: fix rendering bug in board page
  components/board/BoardItem.tsx
  pages/board/index.tsx
Labels: enhancement

#99 Fix : fix dm console error, firebase error
  components/DmButton.tsx
  components/DmChat.tsx
  components/DmListUserName.tsx
  pages/chat/index.tsx
  recoil/dmData.ts
Labels: refactor

#102 Main UI and loading component
  components/MainComment.tsx
  components/MainCommentList.tsx
  components/common/globalModal/Loading.tsx
  package.json
  pages/about/index.tsx
  pages/api/api.ts
  pages/gallery/Post.tsx
  pages/index.tsx
  public/assets/animation/loading.json
  public/assets/icons/main/Fire.png
  yarn.lock
Labels: enhancement

#104 Feat : apply nav button active
  components/DmChat.tsx
  components/SideNav.tsx
  pages/chat/index.tsx
  pages/index.tsx
  public/assets/icons/nav/nav_board_active.svg
  public/assets/icons/nav/nav_gallery_active.svg
  public/assets/icons/nav/nav_home_active.svg
  public/assets/icons/nav/nav_my_active.svg
  public/assets/icons/nav/nav_recruit_active.svg
  styles/theme.ts
Labels: enhancement

#109 Ui : change ui
  components/MainCommentList.tsx
  components/board/BoardItem.tsx
  components/board/BoardPost.tsx
  components/comment/Comment.tsx
  components/comment/CommentList.tsx
  components/common/globalModal/Loading.tsx
  components/gallery/GalleryItem.tsx
  components/mypage/ProfileEdit.tsx
  pages/_document.tsx
  pages/board/Post.tsx
  pages/board/index.tsx
  pages/boardDetail/[...params].tsx
  pages/chat/index.tsx
  pages/gallery/Post.tsx
  pages/gallery/index.tsx
  pages/galleryDetail/[...params].tsx
  pages/index.tsx
  pages/mapBoard/index.tsx
  pages/myPage/[...params].tsx
  pages/recruitDetail/[...params].tsx
  pages/signUp/index.tsx
  styles/theme.ts
Labels: refactor

#117 Refactor: refactor on DM
  components/DmButton.tsx
  components/FollowButton.tsx
  firebase.ts
  pages/recruitDetail/[...params].tsx
Labels: enhancement

#135 UI: modify UI of mapBoard
  components/DmButton.tsx
  components/FollowButton.tsx
  components/comment/CommentList.tsx
  components/common/dropDown/CustomMenu.tsx
  components/common/dropDown/CustomToggle.tsx
  components/mapBoard/RecruitPost.tsx
  components/mapBoard/RecruitPostsWindow.tsx
  components/mapBoard/SearchColleague.tsx
  components/mapBoard/SearchMyGym.tsx
  components/mapBoard/SelectDay.tsx
  firebase.ts
  pages/mapBoard/WritingRecruitment.tsx
  pages/mapBoard/index.tsx
  pages/recruitDetail/[...params].tsx
  public/assets/icons/mapBoard/FistImage.svg
  public/assets/icons/mapBoard/FistImage2.svg
  public/assets/icons/mapBoard/pencil.svg
Labels: enhancement

#140 Fix : fix chat ui
  components/DmButton.tsx
  components/DmListUserName.tsx
  components/chat/DmChat.tsx
  components/chat/DmListUserInfo.tsx
  components/layout/Header.tsx
  components/layout/SideNav.tsx
  pages/_app.tsx
  pages/api/api.ts
  pages/api/chat.ts
  pages/chat/index.tsx
  pages/index.tsx
  public/assets/icons/nav/nav_board_active.svg
  public/assets/icons/nav/nav_chat_active.svg
  public/assets/icons/nav/nav_gallery_active.svg
  public/assets/icons/nav/nav_home_active.svg
  public/assets/icons/nav/nav_my_active.svg
  public/assets/icons/nav/nav_recruit_active.svg
  styles/theme.ts
  types.d.ts
Labels: refactor

#143 Modify UI
  components/DmButton.tsx
  components/board/BoardPost.tsx
  components/common/Like.tsx
  components/common/dropDown/GalleryToggle.tsx
  components/common/globalModal/SearchDropDown.tsx
  components/mapBoard/SearchColleague.tsx
  components/mypage/ProfileUpLoad.tsx
  pages/api/api.ts
  pages/board/Post.tsx
  pages/board/index.tsx
  pages/boardDetail/[...params].tsx
  pages/gallery/Post.tsx
  pages/galleryDetail/[...params].tsx
  pages/myPage/[...params].tsx
  public/assets/icons/dotButton.svg
  public/assets/icons/likeIcon.svg
  public/assets/images/checkedLike.png
  public/assets/images/galleryUploadImage.svg
  public/assets/images/likeImg.png
  public/assets/images/testImg01.png
  public/assets/images/testImg02.png
Labels: help wanted

#142 UI: modify UI of Gallery
  components/gallery/GalleryItem.tsx
  components/gallery/GalleryPost.tsx
  components/mapBoard/RecruitPost.tsx
  components/mapBoard/SearchColleague.tsx
  pages/api/api.ts
  pages/gallery/index.tsx
Labels: enhancement

#160 Fix : fix infinite render
  components/DmButton.tsx
  components/chat/DmChat.tsx
  pages/chat/index.tsx
Labels: refactor

#164 Feat: apply zoom-in, zoom-out button in map
  components/SearchUser.tsx
  components/comment/Comment.tsx
  components/common/dropDown/UseDropDown.tsx
  components/common/globalModal/AlertModal.tsx
  components/common/globalModal/ConfirmModal.tsx
  components/common/globalModal/LoginRequiredModal.tsx
  components/gallery/GalleryPost.tsx
  components/layout/Header.tsx
  components/mapBoard/MapZoomInZoomOut.tsx
  components/mapBoard/SearchColleague.tsx
  components/mapBoard/SearchMyGym.tsx
  components/mapBoard/SelectDay.tsx
  pages/galleryDetail/[...params].tsx
  pages/mapBoard/WritingRecruitment.tsx
  pages/recruitDetail/[...params].tsx
  public/assets/icons/mapBoard/+.svg
  public/assets/icons/mapBoard/-.svg
  test.tsx
  type.ts
Labels: enhancement, refactor
